name: Security Scans Workflow

on: [push]

jobs:
  gitleaks_scan:
    name: Gitleaks Secret Scan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branches: [master] # Example branches, adjust as necessary
    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ matrix.branches }}
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  snyk_scan:
    needs: gitleaks_scan
    runs-on: ubuntu-latest
    name: Snyk Vulnerability Scan
    steps:
      - uses: actions/checkout@v2
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  zap_scan:
    needs: snyk_scan
    runs-on: ubuntu-latest
    name: OWASP ZAP Web Application Scan
    steps:
      - uses: actions/checkout@master
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@master
        with:
          docker_name: 'owasp/zap2docker-stable'
          target: 'http://testphp.vulnweb.com/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
