name: Security Scans Workflow

on: [push]

jobs:
  snyk_scan:
    runs-on: ubuntu-latest
    name: Snyk Vulnerability Scan
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  zap_scan:
    needs: snyk_scan
    runs-on: ubuntu-latest
    name: OWASP ZAP Web Application Scan
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.9.0
        with:
          docker_name: 'owasp/zap2docker-stable'
          target: 'http://testphp.vulnweb.com/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
